// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: checker.proto

package check

import (
	tableaupb "github.com/tableauio/tableau/proto/tableaupb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Issue_Kind int32

const (
	Issue_KIND_UNSPECIFIED   Issue_Kind = 0
	Issue_KIND_LOAD          Issue_Kind = 1
	Issue_KIND_CHECK         Issue_Kind = 2
	Issue_KIND_COMPATIBILITY Issue_Kind = 3
)

// Enum value maps for Issue_Kind.
var (
	Issue_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_LOAD",
		2: "KIND_CHECK",
		3: "KIND_COMPATIBILITY",
	}
	Issue_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":   0,
		"KIND_LOAD":          1,
		"KIND_CHECK":         2,
		"KIND_COMPATIBILITY": 3,
	}
)

func (x Issue_Kind) Enum() *Issue_Kind {
	p := new(Issue_Kind)
	*p = x
	return p
}

func (x Issue_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Issue_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_checker_proto_enumTypes[0].Descriptor()
}

func (Issue_Kind) Type() protoreflect.EnumType {
	return &file_checker_proto_enumTypes[0]
}

func (x Issue_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Issue_Kind.Descriptor instead.
func (Issue_Kind) EnumDescriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{0, 0}
}

type Issue struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Kind          Issue_Kind                  `protobuf:"varint,1,opt,name=kind,proto3,enum=check.Issue_Kind" json:"kind,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Workbook      *tableaupb.WorkbookOptions  `protobuf:"bytes,3,opt,name=workbook,proto3" json:"workbook,omitempty"`
	Worksheet     *tableaupb.WorksheetOptions `protobuf:"bytes,4,opt,name=worksheet,proto3" json:"worksheet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{0}
}

func (x *Issue) GetKind() Issue_Kind {
	if x != nil {
		return x.Kind
	}
	return Issue_KIND_UNSPECIFIED
}

func (x *Issue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Issue) GetWorkbook() *tableaupb.WorkbookOptions {
	if x != nil {
		return x.Workbook
	}
	return nil
}

func (x *Issue) GetWorksheet() *tableaupb.WorksheetOptions {
	if x != nil {
		return x.Worksheet
	}
	return nil
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResult) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

var File_checker_proto protoreflect.FileDescriptor

const file_checker_proto_rawDesc = "" +
	"\n" +
	"\rchecker.proto\x12\x05check\x1a\x1etableau/protobuf/tableau.proto\"\x8c\x02\n" +
	"\x05Issue\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.check.Issue.KindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\bworkbook\x18\x03 \x01(\v2\x18.tableau.WorkbookOptionsR\bworkbook\x127\n" +
	"\tworksheet\x18\x04 \x01(\v2\x19.tableau.WorksheetOptionsR\tworksheet\"S\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKIND_LOAD\x10\x01\x12\x0e\n" +
	"\n" +
	"KIND_CHECK\x10\x02\x12\x16\n" +
	"\x12KIND_COMPATIBILITY\x10\x03\"3\n" +
	"\vCheckResult\x12$\n" +
	"\x06issues\x18\x01 \x03(\v2\f.check.IssueR\x06issuesB$Z\"github.com/tableauio/checker/checkb\x06proto3"

var (
	file_checker_proto_rawDescOnce sync.Once
	file_checker_proto_rawDescData []byte
)

func file_checker_proto_rawDescGZIP() []byte {
	file_checker_proto_rawDescOnce.Do(func() {
		file_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checker_proto_rawDesc), len(file_checker_proto_rawDesc)))
	})
	return file_checker_proto_rawDescData
}

var file_checker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checker_proto_goTypes = []any{
	(Issue_Kind)(0),                    // 0: check.Issue.Kind
	(*Issue)(nil),                      // 1: check.Issue
	(*CheckResult)(nil),                // 2: check.CheckResult
	(*tableaupb.WorkbookOptions)(nil),  // 3: tableau.WorkbookOptions
	(*tableaupb.WorksheetOptions)(nil), // 4: tableau.WorksheetOptions
}
var file_checker_proto_depIdxs = []int32{
	0, // 0: check.Issue.kind:type_name -> check.Issue.Kind
	3, // 1: check.Issue.workbook:type_name -> tableau.WorkbookOptions
	4, // 2: check.Issue.worksheet:type_name -> tableau.WorksheetOptions
	1, // 3: check.CheckResult.issues:type_name -> check.Issue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_checker_proto_init() }
func file_checker_proto_init() {
	if File_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checker_proto_rawDesc), len(file_checker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checker_proto_goTypes,
		DependencyIndexes: file_checker_proto_depIdxs,
		EnumInfos:         file_checker_proto_enumTypes,
		MessageInfos:      file_checker_proto_msgTypes,
	}.Build()
	File_checker_proto = out.File
	file_checker_proto_goTypes = nil
	file_checker_proto_depIdxs = nil
}
