// Code generated by protoc-gen-go-tableau-checker. DO NOT EDIT.
// versions:
// - protoc-gen-go-tableau-checker v0.7.1
// - protoc                        (unknown)

package check

import (
	"encoding/json"
	"errors"

	tableauapi "github.com/tableauio/tableau"
	"github.com/tableauio/tableau/log"
)

// ErrorFormat formats Tableau's structured errors for display.
type ErrorFormat func(*tableauapi.Error) string

// ErrorFormatText uses Tableau's localized text renderer.
var ErrorFormatText ErrorFormat = func(serr *tableauapi.Error) string {
	return serr.Error()
}

// ErrorFormatJSON serializes Tableau's flat error details.
var ErrorFormatJSON ErrorFormat = func(serr *tableauapi.Error) string {
	b, err := json.Marshal(serr)
	if err != nil {
		log.Errorf("failed to marshal error to JSON: %+v", err)
		return ""
	}
	return string(b)
}

// formattedError changes presentation while keeping the Tableau error reachable.
type formattedError struct {
	cause  *tableauapi.Error
	format ErrorFormat
}

func (e *formattedError) Error() string { return e.format(e.cause) }
func (e *formattedError) Unwrap() error { return e.cause }

func newError(failures []error, format ErrorFormat) error {
	serr := tableauapi.Inspect(errors.Join(failures...))
	if serr == nil {
		return nil
	}
	if format == nil {
		return serr
	}
	return &formattedError{cause: serr, format: format}
}
