// Code generated by protoc-gen-go-tableau-checker. DO NOT EDIT.
// versions:
// - protoc-gen-go-tableau-checker v0.7.0
// - protoc                        (unknown)

package check

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/tableauio/tableau/log"
	"github.com/tableauio/tableau/proto/tableaupb"
	"google.golang.org/protobuf/encoding/protojson"
)

// IssueKind is the kind of a check issue.
type IssueKind string

const (
	IssueKindLoad          IssueKind = "load"
	IssueKindCheck         IssueKind = "check"
	IssueKindCompatibility IssueKind = "compatibility"
)

// Issue represents a single structured check error.
type Issue struct {
	Kind      IssueKind                   `json:"kind"`
	Message   string                      `json:"message"`
	Workbook  *tableaupb.WorkbookOptions  `json:"workbook,omitempty"`
	Worksheet *tableaupb.WorksheetOptions `json:"worksheet,omitempty"`
}

// String returns the issue as a human-readable string.
func (i *Issue) String() string {
	return fmt.Sprintf("error: workbook %s, worksheet %s, %s",
		i.Workbook.GetName(),
		i.Worksheet.GetName(),
		i.Message)
}

// MarshalJSON uses protojson for Workbook/Worksheet fields to emit correct proto field names.
func (i *Issue) MarshalJSON() ([]byte, error) {
	marshaler := protojson.MarshalOptions{}
	out := struct {
		Kind      IssueKind       `json:"kind"`
		Message   string          `json:"message"`
		Workbook  json.RawMessage `json:"workbook,omitempty"`
		Worksheet json.RawMessage `json:"worksheet,omitempty"`
	}{
		Kind:    i.Kind,
		Message: i.Message,
	}
	if i.Workbook != nil {
		b, err := marshaler.Marshal(i.Workbook)
		if err != nil {
			return nil, err
		}
		out.Workbook = json.RawMessage(b)
	}
	if i.Worksheet != nil {
		b, err := marshaler.Marshal(i.Worksheet)
		if err != nil {
			return nil, err
		}
		out.Worksheet = json.RawMessage(b)
	}
	return json.Marshal(out)
}

// ErrorFormat is a function type that formats an Error into a string.
type ErrorFormat func(*Error) string

// ErrorFormatText formats issues as human-readable text lines (default).
var ErrorFormatText ErrorFormat = func(e *Error) string {
	msgs := make([]string, len(e.Issues))
	for i, issue := range e.Issues {
		msgs[i] = issue.String()
	}
	return strings.Join(msgs, "\n")
}

// ErrorFormatJSON formats the Error as a JSON object.
var ErrorFormatJSON ErrorFormat = func(e *Error) string {
	b, err := json.Marshal(e)
	if err != nil {
		log.Errorf("failed to marshal Error to JSON: %+v", err)
		return ""
	}
	return string(b)
}

// Error is the error type returned by Check and CheckCompatibility.
type Error struct {
	Issues []*Issue `json:"issues"`
	format ErrorFormat
}

// Error formats the result using the configured ErrorFormat.
// Falls back to ErrorFormatText if format is nil.
func (e *Error) Error() string {
	if e.format == nil {
		return ErrorFormatText(e)
	}
	return e.format(e)
}
