// Code generated by protoc-gen-go-tableau-checker. DO NOT EDIT.
// versions:
// - protoc-gen-go-tableau-checker v0.7.1
// - protoc                        (unknown)

package check

import (
	tableau "github.com/tableauio/checker/test/protoconf/tableau"

	"errors"
	"maps"
	"slices"
	"sync"

	tableauapi "github.com/tableauio/tableau"
	"github.com/tableauio/tableau/format"
	"github.com/tableauio/tableau/load"
	"github.com/tableauio/tableau/log"
	"github.com/tableauio/tableau/proto/tableaupb"
	"google.golang.org/protobuf/proto"
)

type checker interface {
	tableau.Messager
	Check(hub *tableau.Hub) error
	CheckCompatibility(hub, newHub *tableau.Hub) error
}

type checkerGenerator = func() checker
type registrar struct {
	Generators map[string]checkerGenerator
}

func (r *registrar) Register(gen checkerGenerator) {
	msger := gen()
	name := msger.Name()
	if _, ok := r.Generators[name]; ok {
		panic("register duplicate checker: " + name)
	}
	r.Generators[name] = gen
}

var registrarSingleton *registrar
var once sync.Once

func getRegistrar() *registrar {
	once.Do(func() {
		registrarSingleton = &registrar{
			Generators: map[string]checkerGenerator{},
		}
	})
	return registrarSingleton
}

func register(gen checkerGenerator) {
	getRegistrar().Register(gen)
}

type Hub struct {
	*tableau.Hub
	checkers map[string]checker
}

func NewHub(options ...tableau.Option) *Hub {
	return &Hub{
		Hub:      tableau.NewHub(options...),
		checkers: map[string]checker{},
	}
}

const (
	loadTypeDefault = ""
	loadTypeOld     = "(old)"
	loadTypeNew     = "(new)"
)

// load loads all messagers and returns the checker instances that participated
// in this load (keyed by messager name). Callers must assign the returned
// checkers to Hub.checkers when those checkers should drive subsequent Check /
// CheckCompatibility runs. This avoids CheckCompatibility's second load from
// silently overwriting the first load's checkers mid-flight.
func (h *Hub) load(loadType, dir string, f format.Format, options ...load.Option) (map[string]checker, []error) {
	opts := load.ParseOptions(options...)
	messagerMap := h.NewMessagerMap()
	checkers := make(map[string]checker)

	names := slices.Sorted(maps.Keys(messagerMap))
	loadedMessagers := make(tableau.MessagerMap, len(names))
	failures := make([]error, 0, len(names))
	var wg sync.WaitGroup
	var resultMu sync.Mutex
	for _, name := range names {
		msger := messagerMap[name]
		if gen, ok := getRegistrar().Generators[name]; ok {
			c := gen()
			checkers[name] = c
			msger = c.Messager()
		}
		wg.Add(1)
		go func() {
			defer wg.Done()
			log.Infof("=== LOAD  %v%v", name, loadType)
			mopts := opts.ParseMessagerOptionsByName(name)
			if err := msger.Load(dir, f, mopts); err != nil {
				log.Infof("--- FAIL: %v%v", name, loadType)
				failure := newFailure("load"+loadType+" failed", msger, err)
				resultMu.Lock()
				failures = append(failures, failure)
				resultMu.Unlock()
				return
			}
			log.Infof("--- DONE: %v%v", name, loadType)
			resultMu.Lock()
			loadedMessagers[name] = msger
			resultMu.Unlock()
		}()
	}
	wg.Wait()

	h.SetMessagerMap(loadedMessagers)
	// Align with tableau.Hub.Load: after all messagers are loaded, run
	// ProcessAfterLoadAll so derived messagers (e.g. custom conf indexes) can build.
	if len(failures) == 0 {
		for _, name := range names {
			msger := loadedMessagers[name]
			if err := msger.ProcessAfterLoadAll(h.Hub); err != nil {
				failures = append(failures, newFailure("process after load all failed", msger, err))
				log.Infof("--- FAIL: %v%v ProcessAfterLoadAll", name, loadType)
			}
		}
	}
	return checkers, failures
}

// newFailure adds checker context to an independent view of the original error.
func newFailure(prefix string, msger tableau.Messager, err error) *tableauapi.Error {
	serr := tableauapi.Inspect(err)
	workbook, worksheet := getBookAndSheet(msger)
	for _, detail := range serr.Details {
		detail.Message = prefix + ": " + detail.Message
		if detail.Source == nil {
			if workbook.GetName() == "" && worksheet.GetName() == "" {
				continue
			}
			detail.Source = &tableauapi.SourceLocation{}
		}
		if detail.Source.Workbook == "" {
			detail.Source.Workbook = workbook.GetName()
		}
		if detail.Source.Worksheet == "" {
			detail.Source.Worksheet = worksheet.GetName()
		}
	}
	return serr
}

// getBookAndSheet resolves workbook/worksheet options from a messager's
// underlying protobuf message descriptor. Returns nil, nil when the messager
// has no message data (e.g. custom/derived messagers); missing extensions
// also yield nil options.
func getBookAndSheet(msger tableau.Messager) (*tableaupb.WorkbookOptions, *tableaupb.WorksheetOptions) {
	if msger == nil {
		return nil, nil
	}
	msg := msger.Message()
	if msg == nil {
		return nil, nil
	}
	md := msg.ProtoReflect().Descriptor()
	worksheet, _ := proto.GetExtension(md.Options(), tableaupb.E_Worksheet).(*tableaupb.WorksheetOptions)
	workbook, _ := proto.GetExtension(md.ParentFile().Options(), tableaupb.E_Workbook).(*tableaupb.WorkbookOptions)
	return workbook, worksheet
}

func (h *Hub) check(breakFailedCount int) []error {
	failures := make([]error, 0, len(h.checkers))
	for _, name := range slices.Sorted(maps.Keys(h.checkers)) {
		checker := h.checkers[name]
		log.Infof("=== RUN   %v", name)
		err := checker.Check(h.Hub)
		if err != nil {
			failure := newFailure("custom check failed", checker, err)
			log.Errorf("--- FAIL: %v", failure)
			failures = append(failures, failure)
		} else {
			log.Infof("--- PASS: %v", name)
		}
		if breakFailedCount > 0 && len(failures) >= breakFailedCount {
			break
		}
	}
	return failures
}

func (h *Hub) checkCompatibility(newHub *tableau.Hub, breakFailedCount int) []error {
	failures := make([]error, 0, len(h.checkers))
	for _, name := range slices.Sorted(maps.Keys(h.checkers)) {
		checker := h.checkers[name]
		if h.GetMessager(name) == nil || newHub.GetMessager(name) == nil {
			log.Infof("=== SKIP  %v", name)
			continue
		}
		log.Infof("=== RUN   %v", name)
		err := checker.CheckCompatibility(h.Hub, newHub)
		if err != nil {
			failure := newFailure("compatibility check failed", checker, err)
			log.Errorf("--- FAIL: %v", failure)
			failures = append(failures, failure)
		} else {
			log.Infof("--- PASS: %v", name)
		}
		if breakFailedCount > 0 && len(failures) >= breakFailedCount {
			break
		}
	}
	return failures
}

// Check loads configs and runs custom checks, returning joined failures or nil.
// Use tableau.Inspect on the result for structured details and reporting.
func (h *Hub) Check(dir string, format format.Format, options ...Option) error {
	opts := ParseOptions(options...)
	checkers, loadErrors := h.load(loadTypeDefault, dir, format, opts.LoadOptions...)
	if len(loadErrors) > 0 {
		return errors.Join(loadErrors...)
	}
	h.checkers = checkers
	return errors.Join(h.check(opts.BreakFailedCount)...)
}

// CheckCompatibility compares two config snapshots, returning joined failures or nil.
// Use tableau.Inspect on the result for structured details and reporting.
func (h *Hub) CheckCompatibility(dir, newDir string, format format.Format, options ...Option) error {
	opts := ParseOptions(options...)
	// Load new config first; keep its messager map on newHub.
	_, newLoadErrors := h.load(loadTypeNew, newDir, format, opts.LoadOptions...)
	if len(newLoadErrors) > 0 && !opts.SkipLoadErrors {
		return errors.Join(newLoadErrors...)
	}
	newHub := tableau.NewHub()
	newHub.SetMessagerMap(h.GetMessagerMap())
	// Load old config into this hub. Compatibility checkers must own the old
	// messager data, so assign the old checkers explicitly after this load.
	oldCheckers, oldLoadErrors := h.load(loadTypeOld, dir, format, opts.LoadOptions...)
	loadErrors := append(newLoadErrors, oldLoadErrors...)
	if len(oldLoadErrors) > 0 && !opts.SkipLoadErrors {
		return errors.Join(loadErrors...)
	}
	h.checkers = oldCheckers
	compatErrors := h.checkCompatibility(newHub, opts.BreakFailedCount)
	return errors.Join(append(loadErrors, compatErrors...)...)
}

type Options struct {
	// BreakFailedCount breaks the check loop once the number of failed checks
	// reaches this value. Values <= 0 mean never break (run all checkers).
	//
	// Default: 1.
	BreakFailedCount int
	// Deprecated: ProtoPackage is unused. Workbook/worksheet metadata is
	// resolved from each messager's protobuf descriptor.
	//
	// Default: "protoconf".
	ProtoPackage string
	// Whether to ignore errors during loading.
	//
	// Errors may occur during loading old config files when do compatibility
	// check. For example, some new worksheets you recently add are not
	// existed, or proto schema are not compatible, just ignore the loading
	// errors (then these proto message objects are nil after loading), so that
	// compatibility check can continue to run.
	//
	// Default: false.
	SkipLoadErrors bool
	// Options for messager loading.
	//
	// Default: nil.
	LoadOptions []load.Option
}

// Option is the functional option type.
type Option func(*Options)

// BreakFailedCount sets BreakFailedCount option.
// Pass a value <= 0 to run all checkers without early exit.
func BreakFailedCount(count int) Option {
	return func(opts *Options) {
		opts.BreakFailedCount = count
	}
}

// Deprecated: ProtoPackage is unused. Workbook/worksheet metadata is
// resolved from each messager's protobuf descriptor.
func ProtoPackage(protoPackage string) Option {
	return func(opts *Options) {
		opts.ProtoPackage = protoPackage
	}
}

// SkipLoadErrors sets SkipLoadErrors option as true.
func SkipLoadErrors() Option {
	return func(opts *Options) {
		opts.SkipLoadErrors = true
	}
}

// WithLoadOptions sets options for messager loading.
func WithLoadOptions(options ...load.Option) Option {
	return func(opts *Options) {
		opts.LoadOptions = options
	}
}

// newDefault returns a default Options.
func newDefault() *Options {
	return &Options{
		BreakFailedCount: 1,
		ProtoPackage:     "protoconf",
	}
}

// ParseOptions parses functional options and merge them to default Options.
func ParseOptions(setters ...Option) *Options {
	opts := newDefault()
	for _, setter := range setters {
		setter(opts)
	}
	return opts
}
