// Code generated by protoc-gen-go-tableau-checker.
// versions:
// - protoc-gen-go-tableau-checker v0.6.2
// - protoc                        (unknown)
// source: item_conf.proto

package check

import (
	tableau "github.com/tableauio/checker/test/protoconf/tableau"
)

type ItemConf struct {
	tableau.ItemConf
}

func (x *ItemConf) Check(hub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

func (x *ItemConf) CheckCompatibility(hub, newHub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

//nolint:gochecknoinits
func init() {
	register(func() checker { return new(ItemConf) })
}
