// Code generated by protoc-gen-go-tableau-checker.
// versions:
// - protoc-gen-go-tableau-checker v0.6.0
// - protoc                        v3.19.3
// source: test_conf.proto

package check

import (
	"fmt"

	tableau "github.com/tableauio/checker/test/protoconf/tableau"
)

type ActivityConf struct {
	tableau.ActivityConf
}

func (x *ActivityConf) Check(hub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

func (x *ActivityConf) CheckCompatibility(hub, newHub *tableau.Hub) error {
	return fmt.Errorf("load ItemConf successfully even it's checker is not registered\n\nItemConf(old): %v\n\nItemConf(new): %v",
		hub.GetItemConf().Data(), newHub.GetItemConf().Data())
}

type ChapterConf struct {
	tableau.ChapterConf
}

func (x *ChapterConf) Check(hub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

func (x *ChapterConf) CheckCompatibility(hub, newHub *tableau.Hub) error {
	return fmt.Errorf("should not reach here since ChapterConf is not successfully loaded")
}

type ThemeConf struct {
	tableau.ThemeConf
}

func (x *ThemeConf) Check(hub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

func (x *ThemeConf) CheckCompatibility(hub, newHub *tableau.Hub) error {
	return fmt.Errorf("should not reach here since ThemeConf is not successfully loaded")
}

func init() {
	// NOTE: This func is auto-generated. DO NOT EDIT.
	register(func() checker {
		return new(ActivityConf)
	})
	register(func() checker {
		return new(ChapterConf)
	})
	register(func() checker {
		return new(ThemeConf)
	})
}
