// Code generated by protoc-gen-go-tableau-checker.
// versions:
// - protoc-gen-go-tableau-checker v0.4.0
// - protoc                        v3.19.3
// source: test_conf.proto

package check

import (
	tableau "github.com/tableauio/checker/test/protoconf/tableau"
	"github.com/tableauio/tableau/log"
)

type ActivityConf struct {
	tableau.ActivityConf
}

func (x *ActivityConf) Messager() tableau.Messager {
	return &x.ActivityConf
}

func (x *ActivityConf) Check(hub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

func (x *ActivityConf) CheckCompatibility(hub, newHub *tableau.Hub) error {
	log.Infof("ItemConf is correctly loaded even it's checker is not regitstered")
	log.Infof("old: %v\n", hub.GetItemConf().Data())
	log.Infof("new: %v\n", newHub.GetItemConf().Data())
	return nil
}

type ChapterConf struct {
	tableau.ChapterConf
}

func (x *ChapterConf) Messager() tableau.Messager {
	return &x.ChapterConf
}

func (x *ChapterConf) Check(hub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

func (x *ChapterConf) CheckCompatibility(hub, newHub *tableau.Hub) error {
	log.Infof("Should not reach here since ChapterConf is not successfully loaded")
	return nil
}

type ThemeConf struct {
	tableau.ThemeConf
}

func (x *ThemeConf) Messager() tableau.Messager {
	return &x.ThemeConf
}

func (x *ThemeConf) Check(hub *tableau.Hub) error {
	// TODO: implement here.
	return nil
}

func (x *ThemeConf) CheckCompatibility(hub, newHub *tableau.Hub) error {
	log.Infof("Should not reach here since ThemeConf is not successfully loaded")
	return nil
}

func init() {
	// NOTE: This func is auto-generated. DO NOT EDIT.
	Register(func() Checker {
		return new(ActivityConf)
	})
	Register(func() Checker {
		return new(ChapterConf)
	})
	Register(func() Checker {
		return new(ThemeConf)
	})
}
