// Code generated by protoc-gen-go-tableau-checker.
// versions:
// - protoc-gen-go-tableau-checker v0.6.2
// - protoc                        v3.19.3
// source: test_conf.proto

package check

import tableau "github.com/tableauio/checker/test/protoconf/tableau"

type ActivityConf struct {
	UnimplementedChecker
	tableau.ActivityConf
}

type ChapterConf struct {
	UnimplementedChecker
	tableau.ChapterConf
}

type ThemeConf struct {
	UnimplementedChecker
	tableau.ThemeConf
}

func init() {
	// NOTE: This func is auto-generated. DO NOT EDIT.
	register(func() checker {
		return new(ActivityConf)
	})
	register(func() checker {
		return new(ChapterConf)
	})
	register(func() checker {
		return new(ThemeConf)
	})
}
